services:
  worker:
    image: worker
    build:
      target: worker
    
    ports:
      - '3000:3000'
  
  spy:
    image: spy
    build:
      target: spy
    
    depends_on:
      - worker
    
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
  
#  hive:
#    image: hive
#    build:
#      target: hive
#
#    ports:
#      - '8080:80'
