name: Docker

# Only run on push, or PRs modifying Docker, akin to a CD workflow.
on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master
    paths:
      - docker-compose.yaml
      - hive/Dockerfile
      - spy/Dockerfile
      - worker/Dockerfile
      - .github/workflows/docker.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: docker compose build
