name: Documentation

on:
  pull_request:
    branches:
      - master
    paths:
      - hive/**
      - worker/**
      - Cargo.lock
      - Cargo.toml
      - clippy.toml
      - .github/workflows/docs.yaml
      - .cargo/config.toml

env:
  CARGO_TERM_COLOR: always
  RUSTUP_TERM_COLOR: always
  RUSTDOCFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Wasm target
        run: rustup target add wasm32-unknown-unknown
      
      - name: Document Worker
        run: cargo doc --no-deps --document-private-items --package worker
      
      - name: Document Hive
        run: cargo doc --target wasm32-unknown-unknown --no-deps --document-private-items --package hive
