name: Hive

on:
  push:
    branches:
      - master
    paths:
      - hive/**
      - Cargo.lock
      - Cargo.toml
      - .github/workflows/hive.yaml
  
  pull_request:
    branches:
      - master
    paths:
      - hive/**
      - Cargo.lock
      - Cargo.toml
      - .github/workflows/hive.yaml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./hive
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Wasm target
        run: rustup target add wasm32-unknown-unknown
      
      - name: Build
        run: cargo build --target wasm32-unknown-unknown
