name: Hive

on:
  pull_request:
    branches:
      - master
    paths:
      - hive/**
      - Cargo.lock
      - Cargo.toml
      - clippy.toml
      - .github/workflows/hive.yaml
      - .cargo/config.toml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./hive
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Wasm target
        run: rustup target add wasm32-unknown-unknown
        
      - name: Check
        run: cargo clippy --target wasm32-unknown-unknown -- -D warnings
      
      - name: Build
        run: cargo build --target wasm32-unknown-unknown
